CREATE TABLE IF NOT EXISTS discord_weapon_overrides (
  discord_id VARCHAR(32) NOT NULL,
  allow_firearms TINYINT(1) NOT NULL DEFAULT 0,
  deny_firearms  TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (discord_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;